language: node_js
addons:
  sauce_connect: true
env:
  global:
    - SAUCE_USERNAME=gibbs
    - secure: "xnAsgqS5iEweBRQIZcdnRY3YryxzU+NExo28YyeMj7JVpiVCqFg5IXVtj/KtHY7LreeBOB7/OatzJkCHrVVy2ot0KaYLxxITyWTu7ekGMNNz3zjlpHuN3ssYP7OgfWJi+n85Hk/61v2hi6uz6xk6WAIe9L6z9TNMlTWkgl/pINY45eWlhqYzEqYcLmQ1JZSVJKr1jEwNLdH7Hi0rvsgw6wr3GrCXIknkb5V8ftdUyZMr5ERnJe9ZlEiwB27C20bdZF9cIcSKizXnXE0pr3/vlGZHAlUka5DUBLEXldfJ5jOXNBcbDqofMevoEXxChwlwkjf127OPp48hyQDeo7tBCeFfp0moO0ioxviChixv7CzrmD/3RpyJBuhi8MAFbnKlTTG3VdAOZgGhJrWKFbFe4wDHS8PpZ9WT3M/otD+LSgsbjo7Q//PvtU+/9aYdk8b5KAlIL2uDpYefNVIQwFKNixG8vOBQodzYBTb7u/iy5bckM+M4h8OQhJrO+gn1aEldE1yvLBBzC3JvlW0Qs51p/JIKt/+TJboGXwrIpbu0OEracfzS/w2BRovFVH3KtojeKplBTJ66ycJKqHXRaptVMh7sqe3sw1C0E6P98CW789v6HPQ+GbU+auKNHN00l8OitN+7PjUXDD123dijRf5zF7mPrBn3HMiSq5pBnoJkdiI="
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
node_js:
    - "0.12"

